### ISSUE TITLE
README?

### ISSUE THREAD

**Issue by niksingh710** [horriblename/hyprland-touch-gestures#1]
Isn't the readme is of [split-monitor](https://github.com/Duckonaut/split-monitor-workspaces)

**Comment by horriblename** [comment]
i havnt done anything here, can't really do it from a plugin so i gave up

if u really want to, u can use my fork (on branch `gestures-no-lib`) for the time being, it still needs more work to make either a PR/plugin

**Comment by horriblename** [comment]
I should probably explain how to use it

**Comment by horriblename** [comment]
well basically swipe gestures for touchpad also works for touchscreens
